### ISSUE TITLE
Debian 패키지 업데이트 실패 관련되어 확인 부탁드립니다.

### ISSUE THREAD

**Issue by Nevuly** [sparcs-kaist/ftp.kaist.ac.kr#5]
데비안 메인 apt로 사용하려고 하는데, 계속 패키지 업데이트 실패 로그가 쌓인것을 보고 확인이 필요하다 싶어 이슈 태그를 남깁니다.

**Comment by HelloWorld017** [comment]
수정하였습니다. 감사합니다.
